# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0002_auto_20190403_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_caption',
        ),
    ]
